repos:
-   repo: local
    hooks:
    -   id: t-local
        name: test a local hookcheck
        language: system
        entry: python local.py
        stages:
            - "pre-push"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: end-of-file-fixer
        stages:
           - "pre-push"
